// ─── CRMLS City List ───
// All incorporated cities + major unincorporated communities
// in the 6 Southern California counties covered by CRMLS.

export interface CRMLSCity {
  city: string
  county: string
  state: string
  label: string
  searchTerms: string
}

function c(city: string, county: string, extraTerms = ""): CRMLSCity {
  const terms = `${city} ca ${county} ${extraTerms}`.toLowerCase()
  return { city, county, state: "CA", label: `${city}, CA`, searchTerms: terms }
}

const LA = "Los Angeles County"
const OC = "Orange County"
const RV = "Riverside County"
const SB = "San Bernardino County"
const VN = "Ventura County"
const SD = "San Diego County"

export const CRMLS_CITIES: CRMLSCity[] = [
  // ─── Los Angeles County (88 incorporated + unincorporated) ───
  c("Agoura Hills", LA),
  c("Alhambra", LA),
  c("Altadena", LA, "unincorporated"),
  c("Arcadia", LA),
  c("Artesia", LA),
  c("Avalon", LA, "catalina island"),
  c("Azusa", LA),
  c("Baldwin Park", LA),
  c("Bell", LA),
  c("Bell Gardens", LA),
  c("Bellflower", LA),
  c("Beverly Hills", LA, "bh 90210"),
  c("Bradbury", LA),
  c("Burbank", LA),
  c("Calabasas", LA),
  c("Carson", LA),
  c("Cerritos", LA),
  c("Claremont", LA),
  c("Commerce", LA),
  c("Compton", LA),
  c("Covina", LA),
  c("Cudahy", LA),
  c("Culver City", LA),
  c("Diamond Bar", LA),
  c("Downey", LA),
  c("Duarte", LA),
  c("East Los Angeles", LA, "unincorporated east la eastla"),
  c("El Monte", LA),
  c("El Segundo", LA),
  c("Gardena", LA),
  c("Glendale", LA),
  c("Glendora", LA),
  c("Hacienda Heights", LA, "unincorporated"),
  c("Hawaiian Gardens", LA),
  c("Hawthorne", LA),
  c("Hermosa Beach", LA, "south bay"),
  c("Hidden Hills", LA),
  c("Huntington Park", LA),
  c("Industry", LA, "city of industry"),
  c("Inglewood", LA),
  c("Irwindale", LA),
  c("La Cañada Flintridge", LA, "la canada flintridge lcf"),
  c("La Crescenta-Montrose", LA, "unincorporated la crescenta montrose"),
  c("La Habra Heights", LA),
  c("La Mirada", LA),
  c("La Puente", LA),
  c("La Verne", LA),
  c("Lakewood", LA),
  c("Lancaster", LA, "antelope valley av"),
  c("Lawndale", LA),
  c("Lomita", LA),
  c("Long Beach", LA, "lb"),
  c("Los Angeles", LA, "la dtla downtown"),
  c("Lynwood", LA),
  c("Malibu", LA),
  c("Manhattan Beach", LA, "south bay mb"),
  c("Marina del Rey", LA, "unincorporated marina"),
  c("Maywood", LA),
  c("Monrovia", LA),
  c("Montebello", LA),
  c("Monterey Park", LA),
  c("Norwalk", LA),
  c("Palmdale", LA, "antelope valley av"),
  c("Palos Verdes Estates", LA, "pv estates south bay"),
  c("Paramount", LA),
  c("Pasadena", LA),
  c("Pico Rivera", LA),
  c("Pomona", LA),
  c("Rancho Palos Verdes", LA, "rpv south bay"),
  c("Redondo Beach", LA, "south bay"),
  c("Rolling Hills", LA, "south bay"),
  c("Rolling Hills Estates", LA, "south bay"),
  c("Rosemead", LA),
  c("Rowland Heights", LA, "unincorporated"),
  c("San Dimas", LA),
  c("San Fernando", LA),
  c("San Gabriel", LA, "sgv san gabriel valley"),
  c("San Marino", LA),
  c("Santa Clarita", LA, "scv valencia newhall saugus"),
  c("Santa Fe Springs", LA),
  c("Santa Monica", LA, "sm"),
  c("Sierra Madre", LA),
  c("Signal Hill", LA),
  c("South El Monte", LA),
  c("South Gate", LA),
  c("South Pasadena", LA),
  c("Temple City", LA),
  c("Topanga", LA, "unincorporated"),
  c("Torrance", LA, "south bay"),
  c("Vernon", LA),
  c("View Park-Windsor Hills", LA, "unincorporated"),
  c("Walnut", LA),
  c("Walnut Park", LA, "unincorporated"),
  c("West Carson", LA, "unincorporated"),
  c("West Covina", LA),
  c("West Hollywood", LA, "weho"),
  c("Westlake Village", LA),
  c("Whittier", LA),
  c("Willowbrook", LA, "unincorporated"),

  // ─── Orange County (34 incorporated + unincorporated) ───
  c("Aliso Viejo", OC),
  c("Anaheim", OC),
  c("Brea", OC),
  c("Buena Park", OC),
  c("Costa Mesa", OC),
  c("Cypress", OC),
  c("Dana Point", OC),
  c("Fountain Valley", OC),
  c("Fullerton", OC),
  c("Garden Grove", OC),
  c("Huntington Beach", OC, "hb surf city"),
  c("Irvine", OC),
  c("La Habra", OC),
  c("La Palma", OC),
  c("Laguna Beach", OC),
  c("Laguna Hills", OC),
  c("Laguna Niguel", OC),
  c("Laguna Woods", OC),
  c("Lake Forest", OC),
  c("Los Alamitos", OC),
  c("Midway City", OC, "unincorporated"),
  c("Mission Viejo", OC),
  c("Newport Beach", OC, "newport coast"),
  c("Orange", OC),
  c("Placentia", OC),
  c("Rancho Santa Margarita", OC, "rsm"),
  c("Rossmoor", OC, "unincorporated"),
  c("San Clemente", OC),
  c("San Juan Capistrano", OC, "sjc"),
  c("Santa Ana", OC),
  c("Seal Beach", OC),
  c("Stanton", OC),
  c("Trabuco Canyon", OC, "unincorporated"),
  c("Tustin", OC),
  c("Villa Park", OC),
  c("Westminster", OC),
  c("Yorba Linda", OC),

  // ─── Riverside County (28 incorporated + unincorporated) ───
  c("Banning", RV),
  c("Beaumont", RV),
  c("Bermuda Dunes", RV, "unincorporated"),
  c("Blythe", RV),
  c("Calimesa", RV),
  c("Canyon Lake", RV),
  c("Cathedral City", RV, "coachella valley"),
  c("Coachella", RV, "coachella valley"),
  c("Corona", RV),
  c("Desert Hot Springs", RV, "dhs coachella valley"),
  c("Eastvale", RV, "inland empire ie"),
  c("French Valley", RV, "unincorporated"),
  c("Good Hope", RV, "unincorporated"),
  c("Hemet", RV),
  c("Indian Wells", RV, "coachella valley"),
  c("Indio", RV, "coachella valley"),
  c("Jurupa Valley", RV, "inland empire ie"),
  c("La Quinta", RV, "coachella valley"),
  c("Lake Elsinore", RV),
  c("Lake Mathews", RV, "unincorporated"),
  c("Lakeland Village", RV, "unincorporated"),
  c("Mead Valley", RV, "unincorporated"),
  c("Menifee", RV),
  c("Moreno Valley", RV, "inland empire ie"),
  c("Murrieta", RV),
  c("Norco", RV, "inland empire ie"),
  c("Palm Desert", RV, "coachella valley"),
  c("Palm Springs", RV, "coachella valley"),
  c("Perris", RV),
  c("Rancho Mirage", RV, "coachella valley"),
  c("Riverside", RV, "inland empire ie"),
  c("San Jacinto", RV),
  c("Sun City", RV, "unincorporated"),
  c("Temecula", RV, "wine country"),
  c("Temescal Valley", RV, "unincorporated"),
  c("Thermal", RV, "unincorporated coachella valley"),
  c("Thousand Palms", RV, "unincorporated coachella valley"),
  c("Wildomar", RV),
  c("Winchester", RV, "unincorporated"),

  // ─── San Bernardino County (24 incorporated + unincorporated) ───
  c("Adelanto", SB, "high desert"),
  c("Apple Valley", SB, "high desert"),
  c("Barstow", SB, "high desert"),
  c("Big Bear Lake", SB, "mountain"),
  c("Bloomington", SB, "unincorporated inland empire ie"),
  c("Chino", SB, "inland empire ie"),
  c("Chino Hills", SB, "inland empire ie"),
  c("Colton", SB, "inland empire ie"),
  c("Crestline", SB, "unincorporated mountain"),
  c("Devore", SB, "unincorporated"),
  c("Fontana", SB, "inland empire ie"),
  c("Grand Terrace", SB, "inland empire ie"),
  c("Hesperia", SB, "high desert"),
  c("Highland", SB, "inland empire ie"),
  c("Lake Arrowhead", SB, "unincorporated mountain"),
  c("Loma Linda", SB, "inland empire ie"),
  c("Lucerne Valley", SB, "unincorporated high desert"),
  c("Lytle Creek", SB, "unincorporated"),
  c("Montclair", SB, "inland empire ie"),
  c("Muscoy", SB, "unincorporated"),
  c("Needles", SB),
  c("Oak Hills", SB, "unincorporated high desert"),
  c("Ontario", SB, "inland empire ie"),
  c("Phelan", SB, "unincorporated high desert"),
  c("Rancho Cucamonga", SB, "inland empire ie rc"),
  c("Redlands", SB, "inland empire ie"),
  c("Rialto", SB, "inland empire ie"),
  c("Running Springs", SB, "unincorporated mountain"),
  c("San Bernardino", SB, "inland empire ie"),
  c("Twentynine Palms", SB, "29 palms"),
  c("Upland", SB, "inland empire ie"),
  c("Victorville", SB, "high desert"),
  c("Yucaipa", SB),
  c("Yucca Valley", SB),

  // ─── Ventura County (10 incorporated + unincorporated) ───
  c("Bell Canyon", VN, "unincorporated"),
  c("Camarillo", VN),
  c("Casa Conejo", VN, "unincorporated"),
  c("Channel Islands Beach", VN, "unincorporated"),
  c("El Rio", VN, "unincorporated"),
  c("Fillmore", VN),
  c("Meiners Oaks", VN, "unincorporated"),
  c("Mira Monte", VN, "unincorporated"),
  c("Moorpark", VN),
  c("Newbury Park", VN, "unincorporated thousand oaks"),
  c("Oak Park", VN, "unincorporated"),
  c("Oak View", VN, "unincorporated"),
  c("Ojai", VN),
  c("Oxnard", VN),
  c("Piru", VN, "unincorporated"),
  c("Port Hueneme", VN),
  c("San Buenaventura (Ventura)", VN, "ventura"),
  c("Santa Paula", VN),
  c("Simi Valley", VN),
  c("Somis", VN, "unincorporated"),
  c("Thousand Oaks", VN),

  // ─── San Diego County (18 incorporated + unincorporated) ───
  c("Alpine", SD, "unincorporated"),
  c("Bonita", SD, "unincorporated"),
  c("Bonsall", SD, "unincorporated"),
  c("Borrego Springs", SD, "unincorporated"),
  c("Cardiff-by-the-Sea", SD, "unincorporated encinitas"),
  c("Carlsbad", SD),
  c("Chula Vista", SD, "south bay"),
  c("Coronado", SD),
  c("Del Mar", SD),
  c("El Cajon", SD, "east county"),
  c("Encinitas", SD, "north county coastal"),
  c("Escondido", SD, "north county inland"),
  c("Fallbrook", SD, "unincorporated north county"),
  c("Imperial Beach", SD, "ib south bay"),
  c("Jamul", SD, "unincorporated east county"),
  c("La Mesa", SD, "east county"),
  c("Lakeside", SD, "unincorporated east county"),
  c("Lemon Grove", SD),
  c("National City", SD, "south bay"),
  c("Oceanside", SD, "north county coastal"),
  c("Poway", SD),
  c("Ramona", SD, "unincorporated"),
  c("Rancho San Diego", SD, "unincorporated east county"),
  c("Rancho Santa Fe", SD, "unincorporated rsf"),
  c("San Diego", SD, "sd"),
  c("San Marcos", SD, "north county inland"),
  c("San Ysidro", SD, "unincorporated border"),
  c("Santee", SD, "east county"),
  c("Solana Beach", SD, "north county coastal"),
  c("Spring Valley", SD, "unincorporated"),
  c("Valley Center", SD, "unincorporated north county"),
  c("Vista", SD, "north county"),
  c("Winter Gardens", SD, "unincorporated"),
]

export const CRMLS_COUNTIES = [
  "Los Angeles County",
  "Orange County",
  "Riverside County",
  "San Bernardino County",
  "Ventura County",
  "San Diego County",
] as const

export const VALID_CITY_NAMES = new Set(CRMLS_CITIES.map((c) => c.city))
