/**
 * Sample data for branding previews.
 * Uses realistic Beverly Hills data for impressive demos.
 * 
 * Pass B3.1: Sample Report Data Module
 */

export const SAMPLE_REPORT_DATA = {
  market_snapshot: {
    report_type: "market_snapshot",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 30,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Last 30 days",
    counts: {
      Active: 127,
      Pending: 34,
      Closed: 89,
    },
    metrics: {
      median_list_price: 4250000,
      median_close_price: 4150000,
      avg_dom: 42,
      median_dom: 35,
      median_ppsf: 1285,
      months_of_inventory: 4.3,
      list_to_close_ratio: 0.976,
    },
    by_property_type: {
      SFR: { median: 4500000, count: 62, dom: 38 },
      Condo: { median: 2100000, count: 18, dom: 52 },
      Townhome: { median: 2800000, count: 9, dom: 45 },
    },
    price_tiers: {
      entry: { median: 1800000, count: 15, moi: 3.2 },
      move_up: { median: 4200000, count: 52, moi: 4.5 },
      luxury: { median: 12500000, count: 22, moi: 6.8 },
    },
    listings_sample: [
      {
        address: "1234 Sunset Blvd",
        city: "Beverly Hills",
        list_price: 5250000,
        close_price: 5100000,
        beds: 5,
        baths: 6,
        sqft: 4800,
        status: "Active",
        days_on_market: 12,
        list_date: "2025-11-10",
        hero_photo_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      },
      {
        address: "567 Rodeo Drive",
        city: "Beverly Hills",
        list_price: 3850000,
        close_price: 3750000,
        beds: 4,
        baths: 4,
        sqft: 3200,
        status: "Pending",
        days_on_market: 28,
        list_date: "2025-10-28",
        hero_photo_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      },
      {
        address: "890 Canon Drive",
        city: "Beverly Hills",
        list_price: 7200000,
        close_price: 7000000,
        beds: 6,
        baths: 7,
        sqft: 6200,
        status: "Closed",
        days_on_market: 45,
        list_date: "2025-10-01",
        close_date: "2025-11-15",
        hero_photo_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      },
      {
        address: "321 Maple Drive",
        city: "Beverly Hills",
        list_price: 2950000,
        beds: 3,
        baths: 3,
        sqft: 2400,
        status: "Active",
        days_on_market: 8,
        list_date: "2025-11-16",
        hero_photo_url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
      },
      {
        address: "456 Elm Street",
        city: "Beverly Hills",
        list_price: 4100000,
        beds: 4,
        baths: 5,
        sqft: 3800,
        status: "Active",
        days_on_market: 21,
        list_date: "2025-11-03",
        hero_photo_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
      },
      {
        address: "789 Palm Avenue",
        city: "Beverly Hills",
        list_price: 8500000,
        beds: 7,
        baths: 8,
        sqft: 7500,
        status: "Active",
        days_on_market: 35,
        list_date: "2025-10-20",
        hero_photo_url: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
      },
    ],
  },

  new_listings: {
    report_type: "new_listings",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 14,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Last 14 days",
    counts: {
      Active: 42,
      Pending: 8,
      Closed: 0,
    },
    metrics: {
      median_list_price: 4350000,
      avg_dom: 7,
      avg_ppsf: 1320,
    },
    listings_sample: [
      {
        address: "1234 Sunset Blvd",
        city: "Beverly Hills",
        list_price: 5250000,
        beds: 5,
        baths: 6,
        sqft: 4800,
        status: "Active",
        days_on_market: 3,
        list_date: "2025-11-21",
      },
      {
        address: "567 Rodeo Drive",
        city: "Beverly Hills",
        list_price: 3850000,
        beds: 4,
        baths: 4,
        sqft: 3200,
        status: "Active",
        days_on_market: 5,
        list_date: "2025-11-19",
      },
      {
        address: "321 Maple Drive",
        city: "Beverly Hills",
        list_price: 2950000,
        beds: 3,
        baths: 3,
        sqft: 2400,
        status: "Active",
        days_on_market: 8,
        list_date: "2025-11-16",
      },
      {
        address: "456 Elm Street",
        city: "Beverly Hills",
        list_price: 4100000,
        beds: 4,
        baths: 5,
        sqft: 3800,
        status: "Active",
        days_on_market: 10,
        list_date: "2025-11-14",
      },
      {
        address: "789 Palm Avenue",
        city: "Beverly Hills",
        list_price: 8500000,
        beds: 7,
        baths: 8,
        sqft: 7500,
        status: "Active",
        days_on_market: 12,
        list_date: "2025-11-12",
      },
    ],
  },

  new_listings_gallery: {
    report_type: "new_listings_gallery",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 14,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Last 14 days",
    total_listings: 9,
    listings: [
      {
        street_address: "1234 Sunset Blvd",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 5250000,
        bedrooms: 5,
        bathrooms: 6,
        sqft: 4800,
        days_on_market: 3,
        hero_photo_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      },
      {
        street_address: "567 Rodeo Drive",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 3850000,
        bedrooms: 4,
        bathrooms: 4,
        sqft: 3200,
        days_on_market: 5,
        hero_photo_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      },
      {
        street_address: "890 Canon Drive",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 7200000,
        bedrooms: 6,
        bathrooms: 7,
        sqft: 6200,
        days_on_market: 8,
        hero_photo_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      },
      {
        street_address: "321 Maple Drive",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 2950000,
        bedrooms: 3,
        bathrooms: 3,
        sqft: 2400,
        days_on_market: 10,
        hero_photo_url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
      },
      {
        street_address: "456 Elm Street",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 4100000,
        bedrooms: 4,
        bathrooms: 5,
        sqft: 3800,
        days_on_market: 12,
        hero_photo_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
      },
      {
        street_address: "789 Palm Avenue",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 8500000,
        bedrooms: 7,
        bathrooms: 8,
        sqft: 7500,
        days_on_market: 14,
        hero_photo_url: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
      },
    ],
  },

  featured_listings: {
    report_type: "featured_listings",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 30,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Featured Properties",
    total_listings: 4,
    listings: [
      {
        street_address: "1234 Sunset Blvd",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 5250000,
        bedrooms: 5,
        bathrooms: 6,
        sqft: 4800,
        price_per_sqft: 1094,
        days_on_market: 12,
        list_date: "2025-11-10",
        hero_photo_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      },
      {
        street_address: "890 Canon Drive",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 7200000,
        bedrooms: 6,
        bathrooms: 7,
        sqft: 6200,
        price_per_sqft: 1161,
        days_on_market: 18,
        list_date: "2025-11-04",
        hero_photo_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      },
      {
        street_address: "789 Palm Avenue",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 8500000,
        bedrooms: 7,
        bathrooms: 8,
        sqft: 7500,
        price_per_sqft: 1133,
        days_on_market: 25,
        list_date: "2025-10-28",
        hero_photo_url: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
      },
      {
        street_address: "100 Beverly Glen",
        city: "Beverly Hills",
        zip_code: "90210",
        list_price: 12500000,
        bedrooms: 8,
        bathrooms: 10,
        sqft: 9800,
        price_per_sqft: 1276,
        days_on_market: 35,
        list_date: "2025-10-18",
        hero_photo_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      },
    ],
  },

  inventory: {
    report_type: "inventory",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 30,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Current Inventory",
    counts: {
      Active: 127,
      Pending: 34,
      Closed: 0,
    },
    metrics: {
      avg_dom: 45,
      median_dom: 38,
    },
    listings_sample: [],
  },

  closed: {
    report_type: "closed",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 30,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Last 30 days",
    counts: {
      Active: 0,
      Pending: 0,
      Closed: 89,
    },
    metrics: {
      median_close_price: 4150000,
      median_list_price: 4250000,
      avg_dom: 42,
    },
    listings_sample: [],
  },

  price_bands: {
    report_type: "price_bands",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 30,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "Last 30 days",
    metrics: {
      median_list_price: 4250000,
      avg_dom: 42,
    },
    price_bands: [
      { label: "$0 - $2M", count: 18, median_price: 1650000, avg_dom: 28, avg_ppsf: 850 },
      { label: "$2M - $4M", count: 42, median_price: 2950000, avg_dom: 35, avg_ppsf: 1050 },
      { label: "$4M - $6M", count: 35, median_price: 4850000, avg_dom: 42, avg_ppsf: 1250 },
      { label: "$6M - $10M", count: 22, median_price: 7500000, avg_dom: 55, avg_ppsf: 1450 },
      { label: "$10M+", count: 10, median_price: 15000000, avg_dom: 85, avg_ppsf: 1800 },
    ],
  },

  open_houses: {
    report_type: "open_houses",
    city: "Beverly Hills",
    state: "CA",
    lookback_days: 7,
    generated_at: new Date().toISOString(),
    report_date: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    }),
    period_label: "This Weekend",
    counts: {
      Active: 15,
      Pending: 0,
      Closed: 0,
    },
    metrics: {
      avg_dom: 18,
    },
    listings_sample: [],
  },
};

export type ReportType = keyof typeof SAMPLE_REPORT_DATA;

export const REPORT_TYPE_OPTIONS: { value: ReportType; label: string; description: string }[] = [
  { value: "market_snapshot", label: "Market Snapshot", description: "Complete market overview" },
  { value: "new_listings", label: "New Listings", description: "Recently listed properties" },
  { value: "new_listings_gallery", label: "New Listings Gallery", description: "Photo-rich gallery" },
  { value: "featured_listings", label: "Featured Listings", description: "Curated showcase" },
  { value: "inventory", label: "Inventory", description: "Current available properties" },
  { value: "closed", label: "Closed Sales", description: "Recently sold properties" },
  { value: "price_bands", label: "Price Bands", description: "Market by price range" },
  { value: "open_houses", label: "Open Houses", description: "Upcoming open houses" },
];

export function getSampleData(reportType: ReportType) {
  return SAMPLE_REPORT_DATA[reportType];
}

