// ────────────────────────────────────────────────────────────────────────────
// Help Center Content
// Edit this file to update help center content. No React changes needed.
// ────────────────────────────────────────────────────────────────────────────

export interface HelpStep {
  title: string
  body: string
  screenshot?: string
}

export interface HelpArticle {
  id: string
  title: string
  type: "guide" | "faq"
  description?: string
  steps?: HelpStep[]
  question?: string
  answer?: string
}

export interface HelpSection {
  id: string
  title: string
  icon: string
  articles: HelpArticle[]
}

export const HELP_SECTIONS: HelpSection[] = [
  // ── Section 1: Getting Started ──────────────────────────────────────────
  {
    id: "getting-started",
    title: "Getting Started",
    icon: "Rocket",
    articles: [
      {
        id: "agent-setup",
        title: "Agent Account Setup",
        type: "guide",
        description: "Get your agent account ready in under 2 minutes",
        steps: [
          {
            title: "Create your account",
            body: "Sign up at trendyreports.com with your email address. You'll receive a verification email — click the link to activate your account.",
          },
          {
            title: "Complete your profile",
            body: "Add your name, job title, phone number, and headshot photo. This information appears on every report you generate, so make sure it's polished.",
            screenshot: "Profile settings form with photo upload",
          },
          {
            title: "Upload your branding",
            body: "Go to Settings > Branding and upload your company logo (PNG or SVG, at least 400px wide). Choose your primary and accent brand colors using the color picker or enter hex codes directly.",
            screenshot: "Branding settings with logo upload and color picker",
          },
          {
            title: "Generate your first report",
            body: "Click 'New Report' from the dashboard, enter a city or zip code, and choose a report type. Your branding is automatically applied. Preview, then download or send!",
            screenshot: "New report wizard showing city input",
          },
        ],
      },
      {
        id: "affiliate-setup",
        title: "Affiliate (Title Company) Setup",
        type: "guide",
        description: "Set up your affiliate account to sponsor agents",
        steps: [
          {
            title: "Create your affiliate account",
            body: "Register at trendyreports.com and select 'Title Company / Affiliate' as your account type. This gives you access to the affiliate dashboard where you can manage sponsored agents.",
          },
          {
            title: "Configure white-label branding",
            body: "Upload your company logo and set your brand colors in Settings > Branding. This branding will appear on all reports generated by your sponsored agents, either alongside or replacing their own branding.",
            screenshot: "Affiliate branding settings with co-brand toggle",
          },
          {
            title: "Invite your first agent",
            body: "Go to your Affiliate Dashboard and click 'Invite Agent.' Enter their email address and they'll receive an invitation to join with a fully sponsored Pro account at no cost to them.",
          },
          {
            title: "Monitor agent activity",
            body: "Track each sponsored agent's report activity, contact count, and engagement metrics from your dashboard. You can see aggregate statistics without accessing individual contact details.",
            screenshot: "Affiliate dashboard with agent activity cards",
          },
        ],
      },
      {
        id: "gs-faq-setup-time",
        title: "How long does setup take?",
        type: "faq",
        question: "How long does it take to set up my account?",
        answer: "Most users complete setup in under 2 minutes. Just upload your logo, choose your brand colors, and you're ready to create reports. The onboarding checklist on your dashboard guides you through each step.",
      },
      {
        id: "gs-faq-design-skills",
        title: "Design skills needed?",
        type: "faq",
        question: "Do I need any design skills?",
        answer: "No design skills required. Our templates are professionally designed and automatically apply your branding. Just pick a report type and go — the layout, typography, and color scheme are all handled for you.",
      },
    ],
  },

  // ── Section 2: Creating Reports ─────────────────────────────────────────
  {
    id: "creating-reports",
    title: "Creating Reports",
    icon: "FileText",
    articles: [
      {
        id: "create-market-report",
        title: "Create a Market Report",
        type: "guide",
        description: "Generate a branded market report in under 2 minutes",
        steps: [
          {
            title: "Choose your market area",
            body: "Click 'New Report' from your dashboard. Enter a city name, zip code, or neighborhood. We'll pull the latest MLS data automatically for the area you select.",
            screenshot: "Market area selector with city search input",
          },
          {
            title: "Select a report type",
            body: "Choose from 8 report types: Market Snapshot, New Listings Gallery, Featured Listings, Open Houses, Closed Sales, Active Inventory, Price Bands, and New Listings Analytics. Each type is optimized for a different use case.",
            screenshot: "Report type selection cards",
          },
          {
            title: "Pick an audience preset",
            body: "Choose a preset that filters listings for your target audience — First-Time Buyers, Luxury Homes, Family Homes, Condo Watch, Investor Deals, or show all listings with no filters.",
          },
          {
            title: "Preview and deliver",
            body: "Review your report in the preview panel on the right side. When you're happy, download as a print-ready PDF, email it directly to contacts, or both. Your branding is automatically applied.",
            screenshot: "Report preview with delivery options",
          },
        ],
      },
      {
        id: "create-property-report",
        title: "Generate a Property Report",
        type: "guide",
        description: "Create a CMA-style report for listing presentations",
        steps: [
          {
            title: "Enter the property address",
            body: "Navigate to Property Reports and enter the subject property address. We'll pull property details, photos, and nearby comparable sales automatically.",
            screenshot: "Property address input with auto-complete suggestions",
          },
          {
            title: "Select comparable sales",
            body: "Review the suggested comps or manually select up to 6 comparable properties. Adjust the search radius, price range, and property type filters as needed.",
            screenshot: "Comparable sales selection with map view",
          },
          {
            title: "Choose your template",
            body: "Pick from 5 designer templates: Bold, Classic, Elegant, Modern, or Teal. Each template includes your branding, aerial maps, and a QR code that links to a branded lead capture page.",
            screenshot: "Template selection gallery with previews",
          },
          {
            title: "Download or share",
            body: "Download as a print-ready PDF or share via a unique link. The built-in QR code links to a branded landing page that captures leads when prospects scan it at open houses or on flyers.",
            screenshot: "Export options showing PDF download and link sharing",
          },
        ],
      },
      {
        id: "understanding-report-types",
        title: "Understanding Report Types",
        type: "guide",
        description: "Learn which report type works best for each situation",
        steps: [
          {
            title: "Market Snapshot",
            body: "Best for: general market updates. Shows median price, days on market, inventory levels, and a curated selection of listings with photos. Great for monthly email newsletters to your sphere.",
          },
          {
            title: "New Listings Gallery & Featured Listings",
            body: "Best for: showcasing fresh inventory. Displays 6 property cards in a photo grid with prices and details. Use 'Featured Listings' to highlight your own listings, or 'New Listings Gallery' for the latest MLS entries.",
          },
          {
            title: "Closed Sales & Active Inventory",
            body: "Best for: listing presentations and CMAs. Includes a data table with address, beds/baths, square footage, price, and days on market. The Closed Sales report shows sale prices; Active Inventory shows current list prices.",
          },
          {
            title: "Price Bands & New Listings Analytics",
            body: "Best for: investor clients and data-driven buyers. Price Bands breaks down inventory by price range. New Listings Analytics shows month-over-month trends. Both include stat cards and detailed property rows.",
          },
        ],
      },
      {
        id: "cr-faq-mls-data",
        title: "MLS data support",
        type: "faq",
        question: "What MLS data do you support?",
        answer: "We support over 600 MLS systems across the United States. Data is refreshed daily to ensure accuracy. If you need a specific MLS added, contact support@trendyreports.com with the MLS name and we'll prioritize it.",
      },
      {
        id: "cr-faq-edit-report",
        title: "Edit after creating",
        type: "faq",
        question: "Can I edit a report after creating it?",
        answer: "Reports are generated from live MLS data at the time of creation. To get an updated version, simply regenerate the report — it will pull the latest data automatically. Your report history is saved on the dashboard.",
      },
      {
        id: "cr-faq-ai-narrative",
        title: "AI market commentary",
        type: "faq",
        question: "What is the AI Market Insight on my report?",
        answer: "When available, our AI generates a brief market narrative based on the data in your report — summarizing trends, price movements, and inventory changes. This appears as an 'AI Market Insight' section. It's generated automatically and you don't need to write anything.",
      },
    ],
  },

  // ── Section 3: Scheduling Reports ───────────────────────────────────────
  {
    id: "scheduling",
    title: "Scheduling Reports",
    icon: "Calendar",
    articles: [
      {
        id: "setup-automated-delivery",
        title: "Set Up Automated Delivery",
        type: "guide",
        description: "Schedule reports to send automatically on a recurring basis",
        steps: [
          {
            title: "Start a new schedule",
            body: "Go to Schedules and click 'New Schedule.' You'll enter the same report wizard — choose your market area, report type, and audience just like creating a one-time report.",
            screenshot: "Schedule creation wizard step 1",
          },
          {
            title: "Configure the frequency",
            body: "Choose weekly or monthly delivery. For weekly, pick the day of the week. For monthly, pick the date. Then choose the send time and your time zone. Reports are generated with fresh MLS data right before sending.",
            screenshot: "Frequency selector with day, time, and timezone pickers",
          },
          {
            title: "Select recipients",
            body: "Choose individual contacts, entire contact groups, or enter email addresses manually. You can mix and match — for example, a contact group plus a few individual emails. You'll automatically receive a copy.",
            screenshot: "Recipient picker with contacts and groups",
          },
          {
            title: "Activate the schedule",
            body: "Review your schedule summary and click 'Create Schedule.' You'll see the schedule on your Schedules page with the next run date. You can pause, edit, or delete it anytime.",
          },
        ],
      },
      {
        id: "sched-faq-pause",
        title: "Pause a schedule",
        type: "faq",
        question: "Can I pause a scheduled report?",
        answer: "Yes. Go to your Schedules page, find the schedule, and toggle it off. You can resume it anytime without losing your settings. The next send date will be recalculated from when you reactivate.",
      },
      {
        id: "sched-faq-timezone",
        title: "Schedule timezone",
        type: "faq",
        question: "What time zone are schedules based on?",
        answer: "Each schedule uses the time zone you select in the frequency settings. You can choose from all US time zones. The send time shown on the Schedules page reflects this time zone.",
      },
    ],
  },

  // ── Section 4: Managing Contacts ────────────────────────────────────────
  {
    id: "contacts",
    title: "Managing Contacts",
    icon: "Users",
    articles: [
      {
        id: "import-contacts",
        title: "Import and Manage Contacts",
        type: "guide",
        description: "Add contacts individually or import in bulk from CSV",
        steps: [
          {
            title: "Add contacts manually",
            body: "Go to People and click 'Add Contact.' Enter their name, email, phone (optional), and assign them to a group. You can also add contacts directly when sending a report.",
          },
          {
            title: "Import from CSV",
            body: "Go to People and click 'Import.' Drag your CSV file into the upload zone or click to browse. Your CSV should have columns for First Name, Last Name, Email, and optionally Phone and Type (Client or Agent).",
            screenshot: "CSV upload zone with column mapping preview",
          },
          {
            title: "Organize with groups",
            body: "Switch to the Groups tab and click 'New Group.' Name your group (e.g., 'Past Clients,' 'Investors,' 'Open House Leads'), then add contacts to it. Groups make it easy to send reports to the right audience.",
          },
          {
            title: "Send reports to contacts",
            body: "When creating a report or schedule, you can select individual contacts or entire groups as recipients. Contacts also appear in the recipient picker when using the 'Email Report' delivery option.",
          },
        ],
      },
      {
        id: "contacts-faq-groups",
        title: "Create contact groups",
        type: "faq",
        question: "How do I create a contact group?",
        answer: "Go to People, switch to the Groups tab, and click 'New Group.' Give it a name, then add contacts by selecting them from your list. You can also import a CSV directly into a group.",
      },
      {
        id: "contacts-faq-limit",
        title: "Contact limits",
        type: "faq",
        question: "Is there a contact limit?",
        answer: "Starter plan: 100 contacts. Pro plan: 1,000 contacts. Team plan: Unlimited. You can upgrade anytime from Settings > Billing. Duplicates are detected by email address and skipped during import.",
      },
    ],
  },

  // ── Section 5: Lead Capture ─────────────────────────────────────────────
  {
    id: "lead-capture",
    title: "Lead Capture",
    icon: "Target",
    articles: [
      {
        id: "setup-lead-page",
        title: "Set Up Lead Capture",
        type: "guide",
        description: "Use branded landing pages and QR codes to capture leads",
        steps: [
          {
            title: "Understand the flow",
            body: "Every property report includes a QR code and short link. When someone scans the QR code or visits the link, they land on a branded page with your logo and colors. They enter their info and become a lead in your system.",
          },
          {
            title: "Customize your lead page",
            body: "Go to Lead Pages to customize the headline, description, and which fields to collect (name, email, phone). You can also toggle the page on or off. The page automatically shows your branding from Settings > Branding.",
            screenshot: "Lead page editor with field toggles",
          },
          {
            title: "Share the QR code or link",
            body: "Print the QR code on flyers, yard signs, postcards, or business cards. Share the short link via text message, social media, or email signatures. Each property report has its own unique code.",
          },
          {
            title: "Track and follow up with leads",
            body: "When someone fills out the form, you receive an email notification and the lead appears on your Leads page. Each lead is tagged with the source (which property page they came from) so you know what they're interested in.",
            screenshot: "Leads dashboard showing captured leads with source tags",
          },
        ],
      },
      {
        id: "lc-faq-where-leads-go",
        title: "Where leads are stored",
        type: "faq",
        question: "Where do captured leads go?",
        answer: "Leads appear on your dedicated Leads page (accessible from the sidebar) with the date captured and source property. You can also view them under People > Contacts where they're automatically tagged as 'Lead.'",
      },
    ],
  },

  // ── Section 6: Branding & Customization ─────────────────────────────────
  {
    id: "branding",
    title: "Branding & Customization",
    icon: "Palette",
    articles: [
      {
        id: "setup-branding",
        title: "Set Up Your Branding",
        type: "guide",
        description: "Add your logo, colors, and contact information",
        steps: [
          {
            title: "Upload your logo",
            body: "Go to Settings > Branding and upload your company logo. We recommend a PNG or SVG file with a transparent background, at least 400px wide. The logo appears in the header and footer of every report you generate.",
            screenshot: "Logo upload area with drag-and-drop zone",
          },
          {
            title: "Choose your brand colors",
            body: "Select a primary color (used for report headers, buttons, and accents) and a secondary color (used for highlights and subtle accents). Enter hex codes directly or use the visual color picker.",
            screenshot: "Color picker with hex input and preview swatches",
          },
          {
            title: "Complete your contact information",
            body: "Go to Settings > Profile and fill in your name, job title, phone, email, and website. This information appears in the agent footer of every report, so clients always know how to reach you.",
          },
          {
            title: "Preview your branding",
            body: "After saving, create a test report to see how your branding looks in practice. Your logo, colors, name, and contact info are all applied automatically to the report header and footer.",
            screenshot: "Sample report showing branded header and agent footer",
          },
        ],
      },
      {
        id: "brand-faq-multiple",
        title: "Multiple brand profiles",
        type: "faq",
        question: "Can I have different branding for different reports?",
        answer: "Currently, branding is account-wide — all reports use the same logo and colors. Team plan users with sponsored agents can set up co-branding where both the affiliate's and agent's logos appear on reports.",
      },
    ],
  },

  // ── Section 7: Account & Billing ────────────────────────────────────────
  {
    id: "billing",
    title: "Account & Billing",
    icon: "CreditCard",
    articles: [
      {
        id: "billing-faq-upgrade",
        title: "Upgrade plan",
        type: "faq",
        question: "How do I upgrade my plan?",
        answer: "Go to Settings > Billing and click 'Change Plan.' Select your new plan and enter payment details. The upgrade takes effect immediately and you'll be prorated for the remainder of your current billing period.",
      },
      {
        id: "billing-faq-cancel",
        title: "Cancel subscription",
        type: "faq",
        question: "Can I cancel anytime?",
        answer: "Yes, you can cancel anytime from Settings > Billing. Your account will remain active until the end of your current billing period. After that, you'll be downgraded to the free tier with limited report generation.",
      },
      {
        id: "billing-faq-refunds",
        title: "Refund policy",
        type: "faq",
        question: "Do you offer refunds?",
        answer: "We offer a full refund within the first 14 days if you're not satisfied. After that, we don't offer prorated refunds, but you can cancel to prevent future charges. Contact support@trendyreports.com for refund requests.",
      },
      {
        id: "billing-faq-report-limits",
        title: "Report generation limits",
        type: "faq",
        question: "How many reports can I generate per month?",
        answer: "Starter plan: 10 reports/month. Pro plan: 50 reports/month. Team plan: Unlimited. Your current usage is shown in the sidebar and on Settings > Billing. Scheduled reports count toward your monthly limit.",
      },
      {
        id: "billing-faq-payment-methods",
        title: "Payment methods",
        type: "faq",
        question: "What payment methods do you accept?",
        answer: "We accept all major credit cards (Visa, Mastercard, American Express, Discover) through our secure payment processor, Stripe. We don't currently support PayPal, bank transfers, or invoicing.",
      },
    ],
  },

  // ── Section 8: For Affiliates ───────────────────────────────────────────
  {
    id: "affiliates",
    title: "For Affiliates",
    icon: "Building2",
    articles: [
      {
        id: "invite-agent",
        title: "Invite and Manage Agents",
        type: "guide",
        description: "Sponsor agents and manage their accounts from your affiliate dashboard",
        steps: [
          {
            title: "Access your affiliate dashboard",
            body: "Click 'Dashboard' in the sidebar to access your affiliate overview. Here you can see all sponsored agents, their activity levels, and aggregate statistics across your team.",
            screenshot: "Affiliate dashboard with agent cards and metrics",
          },
          {
            title: "Send an agent invitation",
            body: "Click 'Invite Agent' and enter their email address. They'll receive an invitation to create a TrendyReports account with a fully sponsored Pro plan — no cost to them. You can include a personal message with the invitation.",
          },
          {
            title: "Configure co-branding",
            body: "Choose whether your company logo appears alongside each agent's logo on their reports. You can set this as a default for all agents or configure it per agent. Your brand colors can also be applied to agent reports.",
          },
          {
            title: "Track engagement and ROI",
            body: "Monitor each agent's report generation count, email send volume, lead captures, and contact growth from your dashboard. Use these metrics to identify your most active agents and measure your sponsorship ROI.",
            screenshot: "Agent activity analytics with charts",
          },
        ],
      },
      {
        id: "aff-faq-agent-count",
        title: "Agent seat limits",
        type: "faq",
        question: "How many agents can I sponsor?",
        answer: "The Team plan includes unlimited agent seats. Each sponsored agent gets full Pro features (50 reports/month, 1,000 contacts) at no additional cost to them. You're only billed for your own Team plan subscription.",
      },
      {
        id: "aff-faq-agent-visibility",
        title: "Agent data visibility",
        type: "faq",
        question: "Can agents see my dashboard?",
        answer: "No. Agents only see their own reports, contacts, and leads. As an affiliate, you can see aggregate activity metrics (reports generated, emails sent) but not individual contact details or report contents.",
      },
    ],
  },

  // ── Section 9: Troubleshooting ──────────────────────────────────────────
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    icon: "HelpCircle",
    articles: [
      {
        id: "ts-faq-stale-data",
        title: "Stale report data",
        type: "faq",
        question: "My report data looks outdated. What should I do?",
        answer: "MLS data is refreshed daily. If your report shows stale data, regenerate the report to pull the latest numbers. If the data still looks wrong, contact support@trendyreports.com with the city and report type — some MLS feeds may have temporary delays.",
      },
      {
        id: "ts-faq-email-spam",
        title: "Emails going to spam",
        type: "faq",
        question: "Emails are going to spam. How do I fix this?",
        answer: "Ask your recipients to add reports@trendyreports.com to their contacts or safe senders list. This is the most effective fix. If it continues, check that your report doesn't have a misleading subject line. We use authenticated sending (SPF/DKIM) to maximize deliverability.",
      },
      {
        id: "ts-faq-mls-missing",
        title: "Missing MLS area",
        type: "faq",
        question: "I can't find my MLS area. What should I do?",
        answer: "We support 600+ MLS systems, but some smaller or regional boards may not be included yet. Email support@trendyreports.com with your MLS name and service area, and we'll prioritize adding it. Most new MLS integrations are completed within 2 weeks.",
      },
      {
        id: "ts-faq-password-reset",
        title: "Reset password",
        type: "faq",
        question: "How do I reset my password?",
        answer: "Click 'Forgot Password' on the login page and enter your email address. You'll receive a reset link within a few minutes. Check your spam folder if you don't see it. The link expires after 24 hours.",
      },
      {
        id: "ts-faq-report-not-loading",
        title: "Report not loading",
        type: "faq",
        question: "My report is stuck generating. What should I do?",
        answer: "Report generation usually takes 5-15 seconds. If it's been more than a minute, try refreshing the page and regenerating. If the problem persists, check your internet connection and try a different browser. Contact support if it continues.",
      },
      {
        id: "ts-faq-logo-blurry",
        title: "Blurry logo on reports",
        type: "faq",
        question: "My logo looks blurry on the PDF report.",
        answer: "For crisp logos on PDF reports, upload a high-resolution image — at least 400px wide. SVG format works best since it scales perfectly. PNG files should be at least 2x the display size. Avoid JPEG logos as compression artifacts are visible at print resolution.",
      },
      {
        id: "ts-faq-contact-support",
        title: "Contact support",
        type: "faq",
        question: "How do I contact support?",
        answer: "Email support@trendyreports.com with a description of your issue. Include your account email, the report or page you're having trouble with, and any error messages you see. We typically respond within a few hours during business hours (Mon-Fri, 9am-5pm PT).",
      },
    ],
  },
]

export const QUICK_START_ITEMS = [
  { title: "Create Your First Report", icon: "FileText", sectionId: "getting-started" },
  { title: "Set Up Your Branding", icon: "Palette", sectionId: "branding" },
  { title: "Schedule Automated Reports", icon: "Calendar", sectionId: "scheduling" },
  { title: "Invite an Agent", icon: "UserPlus", sectionId: "affiliates" },
]
