type Props = { params: { runId: string } };

export default async function PrintReport({ params }: Props) {
  const { runId } = params;
  return (
    <html lang="en">
      <head>
        <title>Report {runId}</title>
        <style>{`
          @page { size: Letter; margin: 0.5in; }
          body { font-family: ui-sans-serif, system-ui, sans-serif; -webkit-print-color-adjust: exact; }
          h1 { font-size: 22px; margin: 0 0 8px; }
          .section { break-inside: avoid; margin-bottom: 16px; }
          .footer { position: fixed; bottom: 0.3in; font-size: 10px; color: #64748b; }
          .badge { padding: 4px 8px; background: #e2e8f0; display: inline-block; border-radius: 6px; font-size: 12px; }
        `}</style>
      </head>
      <body>
        <div className="section">
          <h1>Market Snapshot</h1>
          <div className="badge">Run ID: {runId}</div>
        </div>
        <div className="section">
          <p>Sample content for PDF rendering. We'll hydrate with real data later.</p>
        </div>
        <div className="footer">Generated by Market Reports</div>
      </body>
    </html>
  );
}

